/* Opera — i quadri, divisi in atti. Ogni atto porta una novita' sola e le da'
   il tempo di sedimentare. Ogni livello e' verificato con una ricerca esaustiva
   in ampiezza: 'par' e' il numero minimo di mosse per risolverlo. */

var OPERA_ACTS = [
  { n: 1, title: "Le punte", note: "La figura si sposta, e ogni quadretto vale solo dove la copre." },
  { n: 2, title: "Il quarto di giro", note: "La figura gira attorno al quadretto premuto." },
  { n: 3, title: "Lo specchio", note: "Assi verticali e orizzontali: la figura si ribalta." },
  { n: 4, title: "Di sbieco", note: "Gli assi possono anche essere obliqui, a 45 gradi." },
  { n: 5, title: "Il mezzo giro", note: "Mezzo giro attorno al perno, in un colpo solo." },
  { n: 6, title: "I muri", note: "Caselle scure: la figura non ci puo' passare sopra." },
  { n: 7, title: "I passi obliqui", note: "Ci si sposta anche in diagonale." },
  { n: 8, title: "L'opera", note: "Tutto insieme, sulle figure piu' larghe." }
];

var OPERA_LEVELS = [
  {
    id: 'q1', n: 1, act: 1, name: "Primo passo", par: 4,
    hint: "Le punte spostano la figura. Un quadretto si può premere solo se la figura ci sta sopra.",
    cols: 4, rows: 4,
    shape: [[0,0],[1,0]],
    target: [[2,2],[3,2]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:0,dy:1} },
      { x:1, y:0, op:{k:'m',dx:1,dy:0} },
      { x:2, y:0, op:{k:'m',dx:1,dy:0} },
      { x:3, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:1, op:{k:'m',dx:0,dy:1} },
      { x:1, y:1, op:{k:'m',dx:1,dy:0} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'q2', n: 2, act: 1, name: "Due caselle", par: 4,
    hint: "Il numero di punte dice di quante caselle ci si sposta.",
    cols: 5, rows: 4,
    shape: [[3,2],[4,2]],
    target: [[0,1],[1,1]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:1,dy:0} },
      { x:2, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:0, op:{k:'m',dx:0,dy:2} },
      { x:0, y:1, op:{k:'m',dx:1,dy:0} },
      { x:1, y:1, op:{k:'m',dx:0,dy:1} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:2, op:{k:'m',dx:1,dy:0} },
      { x:2, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:2, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'q3', n: 3, act: 1, name: "La rincorsa", par: 5,
    hint: "",
    cols: 5, rows: 5,
    shape: [[3,3],[4,3]],
    target: [[2,1],[3,1]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:0,dy:1} },
      { x:0, y:1, op:{k:'m',dx:1,dy:0} },
      { x:1, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:2, op:{k:'m',dx:0,dy:2} },
      { x:2, y:2, op:{k:'m',dx:1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:2} },
      { x:4, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'m',dx:2,dy:0} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:4, op:{k:'m',dx:0,dy:2} },
    ]
  },
  {
    id: 'q4', n: 4, act: 1, name: "Il passo lungo", par: 5,
    hint: "",
    cols: 5, rows: 5,
    shape: [[1,3],[2,3]],
    target: [[0,0],[1,0]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:2,dy:0} },
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:0, y:2, op:{k:'m',dx:2,dy:0} },
      { x:1, y:2, op:{k:'m',dx:0,dy:2} },
      { x:2, y:2, op:{k:'m',dx:-3,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:2} },
      { x:0, y:3, op:{k:'m',dx:-3,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-3} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:3, op:{k:'m',dx:3,dy:0} },
      { x:4, y:3, op:{k:'m',dx:0,dy:1} },
      { x:0, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:4, op:{k:'m',dx:2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:4, op:{k:'m',dx:3,dy:0} },
    ]
  },
  {
    id: 'q5', n: 5, act: 1, name: "Andirivieni", par: 6,
    hint: "",
    cols: 6, rows: 5,
    shape: [[2,2],[3,2]],
    target: [[2,4],[3,4]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:3,dy:0} },
      { x:1, y:0, op:{k:'m',dx:0,dy:1} },
      { x:2, y:0, op:{k:'m',dx:1,dy:0} },
      { x:3, y:0, op:{k:'m',dx:0,dy:3} },
      { x:4, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:1, op:{k:'m',dx:3,dy:0} },
      { x:1, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:4, y:1, op:{k:'m',dx:0,dy:3} },
      { x:1, y:2, op:{k:'m',dx:0,dy:3} },
      { x:2, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:3, op:{k:'m',dx:1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:2,dy:0} },
      { x:3, y:3, op:{k:'m',dx:-3,dy:0} },
      { x:4, y:3, op:{k:'m',dx:0,dy:2} },
      { x:5, y:3, op:{k:'m',dx:2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:1,dy:0} },
      { x:4, y:4, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'q6', n: 6, act: 2, name: "Un quarto di giro", par: 5,
    hint: "La freccia curva gira la figura di un quarto di giro attorno al quadretto premuto.",
    cols: 5, rows: 5,
    shape: [[2,1],[3,1]],
    target: [[2,3],[2,4]],
    walls: [],
    buttons: [
      { x:2, y:0, op:{k:'m',dx:1,dy:0} },
      { x:3, y:0, op:{k:'m',dx:0,dy:1} },
      { x:2, y:1, op:{k:'r',d:90} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:4, y:1, op:{k:'m',dx:1,dy:0} },
      { x:2, y:2, op:{k:'m',dx:1,dy:0} },
      { x:3, y:2, op:{k:'r',d:-90} },
      { x:4, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'r',d:-90} },
      { x:3, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
    ]
  },
  {
    id: 'q7', n: 7, act: 2, name: "Il cardine", par: 6,
    hint: "Il perno è il quadretto premuto: sceglierlo bene cambia tutto.",
    cols: 5, rows: 5,
    shape: [[2,3],[3,3]],
    target: [[2,0],[2,1]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:1,dy:0} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:1, op:{k:'r',d:90} },
      { x:2, y:1, op:{k:'m',dx:0,dy:2} },
      { x:3, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:2, op:{k:'m',dx:2,dy:0} },
      { x:1, y:2, op:{k:'r',d:90} },
      { x:2, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:3, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'q8', n: 8, act: 2, name: "Il perno giusto", par: 6,
    hint: "",
    cols: 6, rows: 5,
    shape: [[1,0],[2,0]],
    target: [[2,0],[2,1]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:0, op:{k:'m',dx:0,dy:2} },
      { x:1, y:1, op:{k:'r',d:-90} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'r',d:90} },
      { x:4, y:1, op:{k:'m',dx:2,dy:0} },
      { x:1, y:2, op:{k:'m',dx:1,dy:0} },
      { x:2, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:3, op:{k:'m',dx:1,dy:0} },
      { x:4, y:3, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'q9', n: 9, act: 2, name: "La stecca", par: 6,
    hint: "",
    cols: 5, rows: 5,
    shape: [[2,2],[3,2],[4,2]],
    target: [[4,0],[4,1],[4,2]],
    walls: [],
    buttons: [
      { x:2, y:0, op:{k:'r',d:-90} },
      { x:3, y:0, op:{k:'m',dx:0,dy:2} },
      { x:4, y:0, op:{k:'m',dx:0,dy:1} },
      { x:0, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:1, op:{k:'m',dx:0,dy:1} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:2, op:{k:'r',d:-90} },
      { x:3, y:2, op:{k:'m',dx:0,dy:1} },
      { x:4, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:3, op:{k:'m',dx:2,dy:0} },
      { x:4, y:3, op:{k:'r',d:90} },
      { x:3, y:4, op:{k:'m',dx:1,dy:0} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-2} },
    ]
  },
  {
    id: 'q10', n: 10, act: 2, name: "Il gomito", par: 7,
    hint: "",
    cols: 5, rows: 5,
    shape: [[3,2],[4,2],[4,3]],
    target: [[3,2],[4,2],[3,3]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'r',d:90} },
      { x:2, y:0, op:{k:'r',d:-90} },
      { x:0, y:1, op:{k:'m',dx:1,dy:0} },
      { x:1, y:1, op:{k:'r',d:-90} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:4, y:1, op:{k:'m',dx:0,dy:2} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:2, op:{k:'r',d:90} },
      { x:2, y:2, op:{k:'m',dx:1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-2} },
    ]
  },
  {
    id: 'q11', n: 11, act: 3, name: "Lo specchio", par: 5,
    hint: "L'asse tratteggiato ribalta la figura, e passa per il quadretto premuto.",
    cols: 5, rows: 5,
    shape: [[0,2],[1,2],[1,3]],
    target: [[0,1],[1,1],[0,2]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'x',a:'v'} },
      { x:1, y:0, op:{k:'m',dx:0,dy:1} },
      { x:2, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:1, op:{k:'m',dx:1,dy:0} },
      { x:1, y:1, op:{k:'x',a:'h'} },
      { x:2, y:1, op:{k:'x',a:'h'} },
      { x:0, y:2, op:{k:'m',dx:1,dy:0} },
      { x:1, y:2, op:{k:'x',a:'h'} },
      { x:2, y:2, op:{k:'x',a:'h'} },
      { x:0, y:3, op:{k:'m',dx:1,dy:0} },
      { x:1, y:3, op:{k:'x',a:'v'} },
    ]
  },
  {
    id: 'q12', n: 12, act: 3, name: "Il riflesso", par: 6,
    hint: "",
    cols: 6, rows: 5,
    shape: [[4,3],[5,3],[5,4]],
    target: [[4,3],[3,4],[4,4]],
    walls: [],
    buttons: [
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:2, op:{k:'x',a:'v'} },
      { x:4, y:2, op:{k:'x',a:'v'} },
      { x:5, y:2, op:{k:'x',a:'v'} },
      { x:3, y:3, op:{k:'x',a:'h'} },
      { x:4, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:0,dy:1} },
      { x:3, y:4, op:{k:'x',a:'v'} },
      { x:4, y:4, op:{k:'m',dx:1,dy:0} },
      { x:5, y:4, op:{k:'m',dx:-2,dy:0} },
    ]
  },
  {
    id: 'q13', n: 13, act: 3, name: "Due specchi", par: 7,
    hint: "",
    cols: 6, rows: 6,
    shape: [[4,2],[5,2],[5,3]],
    target: [[3,3],[4,3],[3,4]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:2, y:0, op:{k:'m',dx:0,dy:1} },
      { x:3, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:1, op:{k:'x',a:'v'} },
      { x:3, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:2, op:{k:'x',a:'h'} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:1} },
      { x:4, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:1,dy:0} },
      { x:3, y:3, op:{k:'x',a:'h'} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:4, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'q14', n: 14, act: 3, name: "La virata", par: 7,
    hint: "",
    cols: 6, rows: 6,
    shape: [[1,2],[2,2],[2,3]],
    target: [[5,4],[4,5],[5,5]],
    walls: [],
    buttons: [
      { x:0, y:2, op:{k:'m',dx:2,dy:0} },
      { x:1, y:2, op:{k:'m',dx:0,dy:1} },
      { x:2, y:2, op:{k:'x',a:'v'} },
      { x:5, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'r',d:90} },
      { x:2, y:3, op:{k:'x',a:'v'} },
      { x:4, y:3, op:{k:'r',d:-90} },
      { x:0, y:4, op:{k:'x',a:'h'} },
      { x:1, y:4, op:{k:'r',d:90} },
      { x:2, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:4, op:{k:'r',d:90} },
      { x:4, y:4, op:{k:'m',dx:2,dy:0} },
      { x:5, y:4, op:{k:'x',a:'h'} },
      { x:1, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:5, op:{k:'m',dx:0,dy:2} },
      { x:3, y:5, op:{k:'r',d:-90} },
      { x:4, y:5, op:{k:'x',a:'v'} },
      { x:5, y:5, op:{k:'m',dx:-2,dy:0} },
    ]
  },
  {
    id: 'q15', n: 15, act: 3, name: "Il ripiego", par: 7,
    hint: "",
    cols: 6, rows: 6,
    shape: [[3,4],[4,4],[5,4]],
    target: [[3,3],[3,4],[3,5]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:2, y:0, op:{k:'x',a:'v'} },
      { x:4, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:1, op:{k:'m',dx:1,dy:0} },
      { x:4, y:1, op:{k:'m',dx:2,dy:0} },
      { x:5, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:2, op:{k:'m',dx:2,dy:0} },
      { x:1, y:2, op:{k:'x',a:'h'} },
      { x:2, y:2, op:{k:'r',d:90} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:2,dy:0} },
      { x:3, y:3, op:{k:'x',a:'h'} },
      { x:5, y:3, op:{k:'x',a:'h'} },
      { x:1, y:4, op:{k:'m',dx:0,dy:2} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:4, op:{k:'r',d:-90} },
      { x:4, y:4, op:{k:'x',a:'h'} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:5, op:{k:'m',dx:2,dy:0} },
      { x:5, y:5, op:{k:'x',a:'h'} },
    ]
  },
  {
    id: 'q16', n: 16, act: 3, name: "Concerto", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[0,2],[0,3],[0,4],[1,4]],
    target: [[2,0],[3,0],[4,0],[4,1]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'x',a:'v'} },
      { x:4, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:0, op:{k:'m',dx:0,dy:1} },
      { x:0, y:1, op:{k:'m',dx:2,dy:0} },
      { x:1, y:1, op:{k:'x',a:'v'} },
      { x:2, y:1, op:{k:'m',dx:0,dy:2} },
      { x:3, y:1, op:{k:'r',d:-90} },
      { x:5, y:1, op:{k:'m',dx:1,dy:0} },
      { x:0, y:2, op:{k:'x',a:'h'} },
      { x:1, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:2, op:{k:'x',a:'h'} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:2, op:{k:'r',d:-90} },
      { x:5, y:2, op:{k:'r',d:90} },
      { x:0, y:3, op:{k:'m',dx:1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:2,dy:0} },
      { x:2, y:3, op:{k:'r',d:90} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:4, op:{k:'m',dx:0,dy:1} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:5, op:{k:'m',dx:0,dy:-2} },
    ]
  },
  {
    id: 'q17', n: 17, act: 4, name: "Di sbieco", par: 5,
    hint: "Gli assi possono essere anche obliqui, a 45 gradi.",
    cols: 5, rows: 5,
    shape: [[1,1],[2,1],[2,2]],
    target: [[3,2],[3,3],[4,3]],
    walls: [],
    buttons: [
      { x:1, y:1, op:{k:'m',dx:0,dy:1} },
      { x:2, y:1, op:{k:'m',dx:0,dy:1} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:0, y:2, op:{k:'m',dx:1,dy:0} },
      { x:1, y:2, op:{k:'x',a:'d1'} },
      { x:2, y:2, op:{k:'x',a:'d2'} },
      { x:3, y:2, op:{k:'x',a:'d2'} },
      { x:0, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:3, op:{k:'x',a:'d2'} },
      { x:4, y:3, op:{k:'m',dx:0,dy:1} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-1} },
    ]
  },
  {
    id: 'q18', n: 18, act: 4, name: "La diagonale", par: 6,
    hint: "",
    cols: 6, rows: 6,
    shape: [[2,3],[3,3],[3,4]],
    target: [[3,3],[3,4],[4,4]],
    walls: [],
    buttons: [
      { x:0, y:1, op:{k:'x',a:'d1'} },
      { x:2, y:1, op:{k:'m',dx:1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:2, op:{k:'x',a:'d2'} },
      { x:2, y:2, op:{k:'x',a:'d2'} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:2, op:{k:'x',a:'d1'} },
      { x:5, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'x',a:'d2'} },
      { x:3, y:3, op:{k:'x',a:'d2'} },
      { x:4, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:4, op:{k:'x',a:'d2'} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:4, op:{k:'x',a:'d2'} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:5, op:{k:'m',dx:0,dy:2} },
      { x:5, y:5, op:{k:'m',dx:0,dy:2} },
    ]
  },
  {
    id: 'q19', n: 19, act: 4, name: "Il taglio", par: 7,
    hint: "",
    cols: 6, rows: 6,
    shape: [[2,1],[3,1],[3,2]],
    target: [[3,4],[2,5],[3,5]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'x',a:'d1'} },
      { x:3, y:0, op:{k:'m',dx:1,dy:0} },
      { x:4, y:0, op:{k:'r',d:-90} },
      { x:1, y:1, op:{k:'m',dx:2,dy:0} },
      { x:2, y:1, op:{k:'x',a:'d2'} },
      { x:3, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:1, op:{k:'x',a:'d1'} },
      { x:5, y:1, op:{k:'x',a:'d1'} },
      { x:2, y:2, op:{k:'m',dx:1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:2} },
      { x:4, y:2, op:{k:'r',d:90} },
      { x:5, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:3, op:{k:'x',a:'d2'} },
      { x:4, y:3, op:{k:'r',d:90} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:4, op:{k:'r',d:90} },
      { x:5, y:4, op:{k:'r',d:-90} },
      { x:2, y:5, op:{k:'m',dx:1,dy:0} },
      { x:3, y:5, op:{k:'r',d:90} },
      { x:4, y:5, op:{k:'m',dx:0,dy:2} },
      { x:5, y:5, op:{k:'m',dx:0,dy:-1} },
    ]
  },
  {
    id: 'q20', n: 20, act: 4, name: "La zeta", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[2,2],[3,2],[1,3],[2,3]],
    target: [[3,2],[3,3],[4,3],[4,4]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:0, op:{k:'x',a:'d2'} },
      { x:2, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:0, op:{k:'m',dx:0,dy:1} },
      { x:5, y:0, op:{k:'m',dx:0,dy:1} },
      { x:1, y:1, op:{k:'m',dx:0,dy:2} },
      { x:2, y:1, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:1, op:{k:'x',a:'d1'} },
      { x:5, y:1, op:{k:'m',dx:0,dy:2} },
      { x:1, y:2, op:{k:'x',a:'h'} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:3, y:2, op:{k:'x',a:'h'} },
      { x:5, y:2, op:{k:'x',a:'v'} },
      { x:0, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'x',a:'v'} },
      { x:3, y:3, op:{k:'x',a:'d1'} },
      { x:4, y:3, op:{k:'x',a:'d2'} },
      { x:5, y:3, op:{k:'x',a:'h'} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:4, op:{k:'x',a:'v'} },
      { x:0, y:5, op:{k:'x',a:'v'} },
      { x:1, y:5, op:{k:'x',a:'v'} },
      { x:2, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:5, op:{k:'x',a:'d2'} },
      { x:4, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:5, op:{k:'x',a:'v'} },
    ]
  },
  {
    id: 'q21', n: 21, act: 4, name: "Doppio taglio", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[1,3],[1,4],[0,5],[1,5]],
    target: [[5,4],[3,5],[4,5],[5,5]],
    walls: [],
    buttons: [
      { x:4, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:2, op:{k:'m',dx:0,dy:2} },
      { x:1, y:2, op:{k:'x',a:'d1'} },
      { x:2, y:2, op:{k:'x',a:'d1'} },
      { x:5, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:3, op:{k:'x',a:'d1'} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'r',d:-90} },
      { x:3, y:3, op:{k:'x',a:'d2'} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:1, y:4, op:{k:'x',a:'d2'} },
      { x:2, y:4, op:{k:'x',a:'d1'} },
      { x:3, y:4, op:{k:'m',dx:0,dy:1} },
      { x:4, y:4, op:{k:'r',d:90} },
      { x:5, y:4, op:{k:'m',dx:0,dy:2} },
      { x:0, y:5, op:{k:'x',a:'d2'} },
      { x:1, y:5, op:{k:'m',dx:1,dy:0} },
      { x:2, y:5, op:{k:'x',a:'d2'} },
      { x:3, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:5, op:{k:'m',dx:0,dy:-1} },
    ]
  },
  {
    id: 'q22', n: 22, act: 4, name: "Il tridente", par: 8,
    hint: "",
    cols: 7, rows: 6,
    shape: [[3,3],[4,3],[5,3],[4,4]],
    target: [[0,3],[0,4],[1,4],[0,5]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:0, op:{k:'m',dx:2,dy:0} },
      { x:4, y:0, op:{k:'x',a:'d1'} },
      { x:5, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:1, op:{k:'r',d:-90} },
      { x:1, y:1, op:{k:'m',dx:1,dy:0} },
      { x:2, y:1, op:{k:'m',dx:1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:2,dy:0} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:6, y:1, op:{k:'r',d:90} },
      { x:1, y:2, op:{k:'x',a:'d2'} },
      { x:4, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:2, op:{k:'m',dx:2,dy:0} },
      { x:0, y:3, op:{k:'x',a:'h'} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'r',d:90} },
      { x:3, y:3, op:{k:'x',a:'d1'} },
      { x:5, y:3, op:{k:'r',d:90} },
      { x:6, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:4, op:{k:'x',a:'v'} },
      { x:3, y:4, op:{k:'r',d:90} },
      { x:4, y:4, op:{k:'x',a:'v'} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:4, op:{k:'x',a:'v'} },
      { x:1, y:5, op:{k:'r',d:-90} },
      { x:3, y:5, op:{k:'x',a:'h'} },
    ]
  },
  {
    id: 'q23', n: 23, act: 5, name: "Il mezzo giro", par: 5,
    hint: "L'arco con due punte fa mezzo giro in un colpo solo.",
    cols: 5, rows: 5,
    shape: [[2,3],[3,3],[3,4]],
    target: [[1,2],[1,3],[2,3]],
    walls: [],
    buttons: [
      { x:0, y:1, op:{k:'m',dx:1,dy:0} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:2, op:{k:'m',dx:1,dy:0} },
      { x:1, y:2, op:{k:'r',d:180} },
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:1,dy:0} },
      { x:3, y:3, op:{k:'r',d:180} },
      { x:4, y:3, op:{k:'r',d:180} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-1} },
    ]
  },
  {
    id: 'q24', n: 24, act: 5, name: "Testa e coda", par: 7,
    hint: "",
    cols: 6, rows: 6,
    shape: [[1,3],[1,4],[1,5],[2,5]],
    target: [[1,3],[2,3],[2,4],[2,5]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:2,dy:0} },
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:0, op:{k:'r',d:180} },
      { x:0, y:1, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:1, op:{k:'m',dx:1,dy:0} },
      { x:4, y:1, op:{k:'m',dx:0,dy:2} },
      { x:1, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:2, op:{k:'m',dx:1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:1} },
      { x:4, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:3, op:{k:'r',d:180} },
      { x:2, y:3, op:{k:'m',dx:0,dy:1} },
      { x:3, y:3, op:{k:'m',dx:1,dy:0} },
      { x:4, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:4, op:{k:'m',dx:2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:2,dy:0} },
      { x:3, y:4, op:{k:'m',dx:1,dy:0} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:5, op:{k:'m',dx:2,dy:0} },
      { x:2, y:5, op:{k:'m',dx:1,dy:0} },
      { x:4, y:5, op:{k:'m',dx:0,dy:1} },
      { x:5, y:5, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'q25', n: 25, act: 5, name: "Il rovescio", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[2,0],[2,1],[1,2],[2,2]],
    target: [[1,2],[2,2],[3,2],[3,3]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:1,dy:0} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:0, op:{k:'m',dx:0,dy:2} },
      { x:4, y:0, op:{k:'r',d:-90} },
      { x:5, y:0, op:{k:'r',d:-90} },
      { x:1, y:1, op:{k:'r',d:-90} },
      { x:2, y:1, op:{k:'m',dx:1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:1, op:{k:'m',dx:0,dy:1} },
      { x:5, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:2, op:{k:'m',dx:0,dy:1} },
      { x:1, y:2, op:{k:'m',dx:2,dy:0} },
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:2, op:{k:'m',dx:0,dy:1} },
      { x:4, y:2, op:{k:'r',d:-90} },
      { x:5, y:2, op:{k:'r',d:90} },
      { x:0, y:3, op:{k:'m',dx:1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'r',d:180} },
      { x:3, y:3, op:{k:'m',dx:0,dy:1} },
      { x:4, y:3, op:{k:'m',dx:0,dy:2} },
      { x:5, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:4, op:{k:'m',dx:1,dy:0} },
      { x:2, y:4, op:{k:'m',dx:2,dy:0} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:5, op:{k:'m',dx:2,dy:0} },
    ]
  },
  {
    id: 'q26', n: 26, act: 5, name: "Il quadrato falso", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[3,3],[4,3],[3,4],[4,4]],
    target: [[1,1],[2,1],[1,2],[2,2]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'r',d:90} },
      { x:1, y:0, op:{k:'x',a:'d2'} },
      { x:2, y:0, op:{k:'m',dx:1,dy:0} },
      { x:4, y:0, op:{k:'r',d:90} },
      { x:5, y:0, op:{k:'r',d:-90} },
      { x:0, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:1, op:{k:'x',a:'d2'} },
      { x:2, y:1, op:{k:'r',d:-90} },
      { x:3, y:1, op:{k:'r',d:180} },
      { x:4, y:1, op:{k:'r',d:-90} },
      { x:5, y:1, op:{k:'m',dx:0,dy:1} },
      { x:0, y:2, op:{k:'x',a:'d1'} },
      { x:1, y:2, op:{k:'m',dx:2,dy:0} },
      { x:3, y:2, op:{k:'r',d:90} },
      { x:4, y:2, op:{k:'r',d:-90} },
      { x:5, y:2, op:{k:'m',dx:0,dy:1} },
      { x:0, y:3, op:{k:'x',a:'d1'} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:3, op:{k:'x',a:'d1'} },
      { x:5, y:3, op:{k:'m',dx:0,dy:1} },
      { x:3, y:4, op:{k:'x',a:'d2'} },
      { x:4, y:4, op:{k:'m',dx:0,dy:1} },
      { x:5, y:4, op:{k:'m',dx:0,dy:1} },
      { x:3, y:5, op:{k:'m',dx:2,dy:0} },
      { x:4, y:5, op:{k:'x',a:'d1'} },
    ]
  },
  {
    id: 'q27', n: 27, act: 5, name: "La girandola", par: 9,
    hint: "",
    cols: 7, rows: 6,
    shape: [[1,2],[2,2],[3,2],[2,3]],
    target: [[2,3],[1,4],[2,4],[2,5]],
    walls: [],
    buttons: [
      { x:2, y:1, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:1, op:{k:'m',dx:1,dy:0} },
      { x:6, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:2, op:{k:'m',dx:1,dy:0} },
      { x:2, y:2, op:{k:'x',a:'v'} },
      { x:3, y:2, op:{k:'m',dx:0,dy:1} },
      { x:4, y:2, op:{k:'x',a:'v'} },
      { x:6, y:2, op:{k:'m',dx:1,dy:0} },
      { x:0, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:1} },
      { x:2, y:3, op:{k:'m',dx:2,dy:0} },
      { x:3, y:3, op:{k:'r',d:-90} },
      { x:4, y:3, op:{k:'x',a:'h'} },
      { x:5, y:3, op:{k:'x',a:'v'} },
      { x:1, y:4, op:{k:'m',dx:1,dy:0} },
      { x:2, y:4, op:{k:'x',a:'h'} },
      { x:3, y:4, op:{k:'x',a:'v'} },
      { x:5, y:4, op:{k:'x',a:'v'} },
      { x:6, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:5, op:{k:'m',dx:1,dy:0} },
      { x:4, y:5, op:{k:'x',a:'v'} },
      { x:5, y:5, op:{k:'m',dx:2,dy:0} },
    ]
  },
  {
    id: 'q28', n: 28, act: 6, name: "Il primo muro", par: 5,
    hint: "Le caselle scure sono muri: la figura non ci passa sopra e non ci gira nemmeno attraverso.",
    cols: 5, rows: 5,
    shape: [[0,3],[1,3],[1,4]],
    target: [[4,2],[3,3],[4,3]],
    walls: [[2,3]],
    buttons: [
      { x:0, y:1, op:{k:'m',dx:0,dy:2} },
      { x:1, y:1, op:{k:'m',dx:0,dy:1} },
      { x:2, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:2, op:{k:'m',dx:0,dy:2} },
      { x:1, y:2, op:{k:'r',d:90} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:3, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:2, op:{k:'r',d:-90} },
      { x:0, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:3, op:{k:'r',d:90} },
      { x:3, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:3, op:{k:'m',dx:1,dy:0} },
      { x:0, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:4, op:{k:'m',dx:2,dy:0} },
    ]
  },
  {
    id: 'q29', n: 29, act: 6, name: "Lo stretto", par: 7,
    hint: "",
    cols: 6, rows: 6,
    shape: [[0,1],[0,2],[0,3],[1,3]],
    target: [[3,1],[4,1],[4,2],[4,3]],
    walls: [[4,4]],
    buttons: [
      { x:0, y:1, op:{k:'m',dx:0,dy:1} },
      { x:1, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:1, op:{k:'m',dx:0,dy:1} },
      { x:5, y:1, op:{k:'m',dx:0,dy:2} },
      { x:0, y:2, op:{k:'m',dx:2,dy:0} },
      { x:2, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:1} },
      { x:4, y:2, op:{k:'r',d:-90} },
      { x:5, y:2, op:{k:'r',d:-90} },
      { x:0, y:3, op:{k:'r',d:-90} },
      { x:1, y:3, op:{k:'r',d:90} },
      { x:2, y:3, op:{k:'m',dx:1,dy:0} },
      { x:3, y:3, op:{k:'r',d:-90} },
      { x:5, y:3, op:{k:'m',dx:0,dy:1} },
      { x:1, y:4, op:{k:'m',dx:2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:5, op:{k:'m',dx:0,dy:2} },
      { x:4, y:5, op:{k:'m',dx:0,dy:-2} },
    ]
  },
  {
    id: 'q30', n: 30, act: 6, name: "La colonna", par: 9,
    hint: "",
    cols: 7, rows: 6,
    shape: [[3,0],[3,1],[2,2],[3,2]],
    target: [[4,2],[4,3],[5,3],[6,3]],
    walls: [[2,3],[5,4]],
    buttons: [
      { x:2, y:0, op:{k:'m',dx:0,dy:1} },
      { x:3, y:0, op:{k:'m',dx:0,dy:1} },
      { x:4, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:0, op:{k:'m',dx:2,dy:0} },
      { x:6, y:0, op:{k:'r',d:90} },
      { x:1, y:1, op:{k:'m',dx:0,dy:2} },
      { x:2, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:1, op:{k:'r',d:90} },
      { x:4, y:1, op:{k:'r',d:90} },
      { x:5, y:1, op:{k:'m',dx:1,dy:0} },
      { x:6, y:1, op:{k:'r',d:90} },
      { x:1, y:2, op:{k:'m',dx:1,dy:0} },
      { x:3, y:2, op:{k:'x',a:'v'} },
      { x:4, y:2, op:{k:'x',a:'h'} },
      { x:5, y:2, op:{k:'r',d:-90} },
      { x:1, y:3, op:{k:'x',a:'v'} },
      { x:3, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:3, op:{k:'m',dx:0,dy:2} },
      { x:4, y:4, op:{k:'x',a:'v'} },
      { x:6, y:4, op:{k:'m',dx:0,dy:1} },
    ]
  },
  {
    id: 'q31', n: 31, act: 6, name: "La doppia vu", par: 9,
    hint: "",
    cols: 7, rows: 7,
    shape: [[2,2],[2,3],[3,3],[3,4],[4,4]],
    target: [[4,3],[5,3],[3,4],[4,4],[3,5]],
    walls: [[3,1]],
    buttons: [
      { x:2, y:0, op:{k:'x',a:'h'} },
      { x:3, y:0, op:{k:'x',a:'v'} },
      { x:4, y:0, op:{k:'m',dx:0,dy:1} },
      { x:5, y:0, op:{k:'r',d:90} },
      { x:6, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:1, op:{k:'r',d:90} },
      { x:4, y:1, op:{k:'m',dx:1,dy:0} },
      { x:5, y:1, op:{k:'x',a:'v'} },
      { x:6, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:2, op:{k:'r',d:90} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:4, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:2, op:{k:'m',dx:1,dy:0} },
      { x:0, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:2} },
      { x:3, y:3, op:{k:'r',d:90} },
      { x:4, y:3, op:{k:'x',a:'h'} },
      { x:5, y:3, op:{k:'x',a:'v'} },
      { x:6, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:4, op:{k:'m',dx:0,dy:1} },
      { x:2, y:4, op:{k:'r',d:-90} },
      { x:3, y:4, op:{k:'x',a:'h'} },
      { x:4, y:4, op:{k:'r',d:-90} },
      { x:6, y:4, op:{k:'x',a:'v'} },
      { x:0, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:5, op:{k:'x',a:'h'} },
      { x:3, y:5, op:{k:'m',dx:0,dy:2} },
      { x:4, y:5, op:{k:'x',a:'h'} },
      { x:5, y:5, op:{k:'x',a:'h'} },
      { x:0, y:6, op:{k:'x',a:'v'} },
      { x:1, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:6, op:{k:'x',a:'h'} },
      { x:3, y:6, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:6, op:{k:'x',a:'v'} },
      { x:5, y:6, op:{k:'m',dx:1,dy:0} },
      { x:6, y:6, op:{k:'m',dx:0,dy:1} },
    ]
  },
  {
    id: 'q32', n: 32, act: 6, name: "Ferro di cavallo", par: 10,
    hint: "",
    cols: 7, rows: 7,
    shape: [[4,4],[6,4],[4,5],[5,5],[6,5]],
    target: [[0,3],[1,3],[2,3],[0,4],[2,4]],
    walls: [[1,1],[1,4]],
    buttons: [
      { x:2, y:0, op:{k:'x',a:'d1'} },
      { x:3, y:0, op:{k:'r',d:-90} },
      { x:5, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:0, op:{k:'m',dx:0,dy:2} },
      { x:0, y:1, op:{k:'m',dx:2,dy:0} },
      { x:2, y:1, op:{k:'x',a:'h'} },
      { x:3, y:1, op:{k:'x',a:'d2'} },
      { x:4, y:1, op:{k:'r',d:-90} },
      { x:5, y:1, op:{k:'x',a:'d1'} },
      { x:6, y:1, op:{k:'x',a:'d2'} },
      { x:0, y:2, op:{k:'x',a:'h'} },
      { x:1, y:2, op:{k:'m',dx:0,dy:1} },
      { x:2, y:2, op:{k:'r',d:90} },
      { x:3, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:2, op:{k:'m',dx:2,dy:0} },
      { x:0, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:3, op:{k:'x',a:'d2'} },
      { x:4, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:3, op:{k:'m',dx:0,dy:2} },
      { x:6, y:3, op:{k:'r',d:90} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:2, y:4, op:{k:'r',d:90} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:6, y:4, op:{k:'x',a:'d2'} },
      { x:0, y:5, op:{k:'m',dx:0,dy:1} },
      { x:1, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:5, op:{k:'m',dx:2,dy:0} },
      { x:4, y:5, op:{k:'x',a:'v'} },
      { x:1, y:6, op:{k:'m',dx:1,dy:0} },
      { x:2, y:6, op:{k:'m',dx:2,dy:0} },
      { x:3, y:6, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:6, op:{k:'r',d:90} },
    ]
  },
  {
    id: 'q33', n: 33, act: 7, name: "Il passo obliquo", par: 6,
    hint: "Qui tutte le frecce sono oblique: da questo quadro ci si sposta anche in diagonale.",
    cols: 6, rows: 6,
    shape: [[1,3],[2,3],[2,4]],
    target: [[3,3],[4,3],[4,4]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:2,dy:2} },
      { x:2, y:0, op:{k:'m',dx:1,dy:1} },
      { x:3, y:0, op:{k:'m',dx:-1,dy:1} },
      { x:1, y:1, op:{k:'m',dx:1,dy:-1} },
      { x:2, y:1, op:{k:'m',dx:1,dy:1} },
      { x:3, y:1, op:{k:'m',dx:2,dy:-2} },
      { x:4, y:1, op:{k:'m',dx:1,dy:1} },
      { x:2, y:2, op:{k:'m',dx:1,dy:-1} },
      { x:3, y:2, op:{k:'m',dx:1,dy:1} },
      { x:4, y:2, op:{k:'m',dx:-2,dy:2} },
      { x:5, y:2, op:{k:'m',dx:-2,dy:-2} },
      { x:1, y:3, op:{k:'m',dx:-1,dy:1} },
      { x:2, y:3, op:{k:'m',dx:2,dy:-2} },
      { x:3, y:3, op:{k:'m',dx:-2,dy:-2} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:-2} },
      { x:5, y:3, op:{k:'m',dx:1,dy:1} },
      { x:0, y:4, op:{k:'m',dx:-2,dy:-2} },
      { x:1, y:4, op:{k:'m',dx:-2,dy:2} },
      { x:2, y:4, op:{k:'m',dx:2,dy:-2} },
      { x:1, y:5, op:{k:'m',dx:2,dy:2} },
      { x:3, y:5, op:{k:'m',dx:-2,dy:2} },
    ]
  },
  {
    id: 'q34', n: 34, act: 7, name: "A sghembo", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[0,3],[0,4],[0,5],[1,5]],
    target: [[2,2],[3,2],[3,3],[3,4]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'r',d:-90} },
      { x:1, y:0, op:{k:'m',dx:2,dy:-2} },
      { x:4, y:0, op:{k:'r',d:90} },
      { x:5, y:0, op:{k:'m',dx:0,dy:2} },
      { x:0, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:1, op:{k:'m',dx:-1,dy:-1} },
      { x:2, y:1, op:{k:'m',dx:2,dy:0} },
      { x:3, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:1, op:{k:'m',dx:0,dy:1} },
      { x:5, y:1, op:{k:'m',dx:-2,dy:2} },
      { x:0, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:2, op:{k:'m',dx:0,dy:2} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:3, op:{k:'m',dx:0,dy:1} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'m',dx:-2,dy:-2} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:3, op:{k:'r',d:-90} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:4, op:{k:'m',dx:2,dy:-2} },
      { x:3, y:4, op:{k:'m',dx:-2,dy:-2} },
      { x:4, y:4, op:{k:'r',d:90} },
      { x:5, y:4, op:{k:'m',dx:-1,dy:-1} },
      { x:0, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:5, op:{k:'m',dx:0,dy:1} },
      { x:5, y:5, op:{k:'m',dx:0,dy:-1} },
    ]
  },
  {
    id: 'q35', n: 35, act: 7, name: "La scacchiera", par: 9,
    hint: "",
    cols: 7, rows: 7,
    shape: [[3,4],[4,4],[2,5],[3,5]],
    target: [[1,3],[0,4],[1,4],[0,5]],
    walls: [],
    buttons: [
      { x:2, y:1, op:{k:'m',dx:1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:-2,dy:2} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:1, op:{k:'m',dx:0,dy:-2} },
      { x:6, y:1, op:{k:'m',dx:-2,dy:-2} },
      { x:0, y:2, op:{k:'x',a:'v'} },
      { x:2, y:2, op:{k:'m',dx:-2,dy:2} },
      { x:3, y:2, op:{k:'m',dx:0,dy:2} },
      { x:4, y:2, op:{k:'m',dx:1,dy:0} },
      { x:5, y:2, op:{k:'m',dx:1,dy:1} },
      { x:6, y:2, op:{k:'m',dx:1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:-2,dy:-2} },
      { x:2, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:3, op:{k:'m',dx:2,dy:0} },
      { x:4, y:3, op:{k:'x',a:'h'} },
      { x:5, y:3, op:{k:'m',dx:-1,dy:1} },
      { x:6, y:3, op:{k:'m',dx:2,dy:2} },
      { x:0, y:4, op:{k:'m',dx:-2,dy:2} },
      { x:1, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:4, op:{k:'r',d:-90} },
      { x:4, y:4, op:{k:'x',a:'h'} },
      { x:5, y:4, op:{k:'m',dx:-1,dy:1} },
      { x:6, y:4, op:{k:'m',dx:2,dy:-2} },
      { x:0, y:5, op:{k:'r',d:90} },
      { x:1, y:5, op:{k:'m',dx:2,dy:0} },
      { x:2, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:5, op:{k:'x',a:'h'} },
      { x:4, y:5, op:{k:'x',a:'v'} },
      { x:5, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:6, op:{k:'m',dx:0,dy:2} },
      { x:1, y:6, op:{k:'x',a:'v'} },
      { x:2, y:6, op:{k:'m',dx:1,dy:0} },
      { x:3, y:6, op:{k:'m',dx:-1,dy:-1} },
      { x:4, y:6, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:6, op:{k:'m',dx:-1,dy:-1} },
    ]
  },
  {
    id: 'q36', n: 36, act: 7, name: "Effe", par: 10,
    hint: "",
    cols: 7, rows: 7,
    shape: [[3,3],[4,3],[2,4],[3,4],[3,5]],
    target: [[2,1],[1,2],[2,2],[3,2],[1,3]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:-2,dy:2} },
      { x:2, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:0, op:{k:'m',dx:-1,dy:1} },
      { x:1, y:1, op:{k:'m',dx:2,dy:2} },
      { x:2, y:1, op:{k:'x',a:'v'} },
      { x:4, y:1, op:{k:'m',dx:-1,dy:1} },
      { x:5, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:1, op:{k:'m',dx:2,dy:0} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:2, op:{k:'m',dx:1,dy:1} },
      { x:2, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:1} },
      { x:4, y:2, op:{k:'m',dx:2,dy:0} },
      { x:0, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:-1,dy:1} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:3, op:{k:'x',a:'h'} },
      { x:5, y:3, op:{k:'m',dx:1,dy:1} },
      { x:1, y:4, op:{k:'m',dx:2,dy:-2} },
      { x:2, y:4, op:{k:'m',dx:0,dy:1} },
      { x:4, y:4, op:{k:'m',dx:-1,dy:-1} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:5, op:{k:'m',dx:1,dy:-1} },
      { x:3, y:5, op:{k:'x',a:'v'} },
      { x:4, y:5, op:{k:'m',dx:2,dy:-2} },
      { x:5, y:5, op:{k:'m',dx:-1,dy:1} },
      { x:6, y:5, op:{k:'m',dx:2,dy:2} },
      { x:0, y:6, op:{k:'m',dx:1,dy:0} },
      { x:2, y:6, op:{k:'r',d:-90} },
      { x:3, y:6, op:{k:'m',dx:1,dy:-1} },
      { x:4, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:6, op:{k:'r',d:-90} },
    ]
  },
  {
    id: 'q37', n: 37, act: 7, name: "La enne", par: 10,
    hint: "",
    cols: 7, rows: 7,
    shape: [[5,1],[4,2],[5,2],[4,3],[4,4]],
    target: [[1,3],[1,4],[2,4],[2,5],[2,6]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'r',d:90} },
      { x:2, y:0, op:{k:'r',d:-90} },
      { x:1, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:1, op:{k:'x',a:'d1'} },
      { x:4, y:1, op:{k:'r',d:90} },
      { x:5, y:1, op:{k:'m',dx:0,dy:1} },
      { x:6, y:1, op:{k:'x',a:'d1'} },
      { x:1, y:2, op:{k:'m',dx:2,dy:0} },
      { x:2, y:2, op:{k:'r',d:180} },
      { x:3, y:2, op:{k:'m',dx:0,dy:1} },
      { x:4, y:2, op:{k:'m',dx:2,dy:0} },
      { x:5, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:6, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'r',d:-90} },
      { x:2, y:3, op:{k:'m',dx:0,dy:2} },
      { x:3, y:3, op:{k:'m',dx:1,dy:0} },
      { x:4, y:3, op:{k:'x',a:'d2'} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:6, y:3, op:{k:'x',a:'d2'} },
      { x:1, y:4, op:{k:'x',a:'d2'} },
      { x:2, y:4, op:{k:'m',dx:2,dy:0} },
      { x:3, y:4, op:{k:'x',a:'d1'} },
      { x:4, y:4, op:{k:'x',a:'d1'} },
      { x:5, y:4, op:{k:'m',dx:0,dy:1} },
      { x:6, y:4, op:{k:'r',d:-90} },
      { x:1, y:5, op:{k:'m',dx:0,dy:1} },
      { x:4, y:5, op:{k:'m',dx:0,dy:2} },
      { x:5, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:6, op:{k:'x',a:'d1'} },
      { x:1, y:6, op:{k:'r',d:-90} },
      { x:2, y:6, op:{k:'m',dx:2,dy:0} },
      { x:3, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:6, y:6, op:{k:'m',dx:0,dy:2} },
    ]
  },
  {
    id: 'q38', n: 38, act: 8, name: "La ipsilon", par: 11,
    hint: "",
    cols: 7, rows: 7,
    shape: [[4,1],[3,2],[4,2],[4,3],[4,4]],
    target: [[5,2],[5,3],[6,3],[5,4],[5,5]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:1,dy:0} },
      { x:2, y:0, op:{k:'x',a:'v'} },
      { x:4, y:0, op:{k:'m',dx:1,dy:0} },
      { x:6, y:0, op:{k:'x',a:'d1'} },
      { x:0, y:1, op:{k:'m',dx:2,dy:0} },
      { x:1, y:1, op:{k:'m',dx:0,dy:2} },
      { x:2, y:1, op:{k:'r',d:-90} },
      { x:3, y:1, op:{k:'x',a:'h'} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:6, y:1, op:{k:'m',dx:1,dy:0} },
      { x:0, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:2, op:{k:'x',a:'v'} },
      { x:2, y:2, op:{k:'r',d:90} },
      { x:3, y:2, op:{k:'m',dx:0,dy:2} },
      { x:4, y:2, op:{k:'m',dx:0,dy:2} },
      { x:5, y:2, op:{k:'x',a:'d2'} },
      { x:6, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:3, op:{k:'x',a:'d1'} },
      { x:1, y:3, op:{k:'x',a:'v'} },
      { x:2, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:6, y:3, op:{k:'x',a:'h'} },
      { x:0, y:4, op:{k:'r',d:90} },
      { x:3, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:4, op:{k:'x',a:'v'} },
      { x:5, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:6, y:4, op:{k:'r',d:-90} },
      { x:0, y:5, op:{k:'x',a:'d1'} },
      { x:1, y:5, op:{k:'x',a:'v'} },
      { x:5, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:0, y:6, op:{k:'m',dx:0,dy:1} },
      { x:2, y:6, op:{k:'m',dx:2,dy:0} },
      { x:3, y:6, op:{k:'m',dx:0,dy:2} },
      { x:4, y:6, op:{k:'m',dx:-2,dy:0} },
    ]
  },
  {
    id: 'q39', n: 39, act: 8, name: "La zeta lunga", par: 12,
    hint: "",
    cols: 7, rows: 7,
    shape: [[2,0],[3,0],[3,1],[3,2],[4,2]],
    target: [[1,0],[2,0],[1,1],[0,2],[1,2]],
    walls: [[5,3],[3,5]],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:-3,dy:0} },
      { x:1, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:0, op:{k:'m',dx:2,dy:0} },
      { x:6, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:1, op:{k:'m',dx:0,dy:2} },
      { x:1, y:1, op:{k:'m',dx:3,dy:0} },
      { x:2, y:1, op:{k:'x',a:'d1'} },
      { x:3, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:1, op:{k:'m',dx:-3,dy:0} },
      { x:5, y:1, op:{k:'m',dx:0,dy:3} },
      { x:6, y:1, op:{k:'r',d:180} },
      { x:1, y:2, op:{k:'r',d:90} },
      { x:3, y:2, op:{k:'m',dx:1,dy:0} },
      { x:4, y:2, op:{k:'m',dx:0,dy:-3} },
      { x:6, y:2, op:{k:'x',a:'d1'} },
      { x:0, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:3, op:{k:'x',a:'d2'} },
      { x:3, y:3, op:{k:'x',a:'d1'} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:4, op:{k:'x',a:'d2'} },
      { x:3, y:4, op:{k:'r',d:180} },
      { x:4, y:4, op:{k:'r',d:180} },
      { x:5, y:4, op:{k:'m',dx:0,dy:1} },
      { x:0, y:5, op:{k:'r',d:180} },
      { x:1, y:5, op:{k:'m',dx:0,dy:1} },
      { x:2, y:5, op:{k:'m',dx:0,dy:3} },
      { x:4, y:5, op:{k:'m',dx:0,dy:-3} },
      { x:5, y:5, op:{k:'x',a:'d1'} },
      { x:1, y:6, op:{k:'m',dx:1,dy:0} },
      { x:2, y:6, op:{k:'m',dx:0,dy:3} },
      { x:3, y:6, op:{k:'m',dx:1,dy:0} },
    ]
  },
  {
    id: 'q40', n: 40, act: 8, name: "La croce", par: 13,
    hint: "",
    cols: 7, rows: 7,
    shape: [[2,3],[3,3],[4,3],[3,4],[3,5]],
    target: [[3,1],[3,2],[4,2],[5,2],[3,3]],
    walls: [[2,1],[1,5]],
    buttons: [
      { x:2, y:0, op:{k:'m',dx:2,dy:0} },
      { x:3, y:0, op:{k:'r',d:90} },
      { x:4, y:0, op:{k:'x',a:'v'} },
      { x:5, y:0, op:{k:'m',dx:1,dy:1} },
      { x:6, y:0, op:{k:'r',d:-90} },
      { x:0, y:1, op:{k:'m',dx:1,dy:0} },
      { x:4, y:1, op:{k:'x',a:'h'} },
      { x:5, y:1, op:{k:'x',a:'d2'} },
      { x:6, y:1, op:{k:'m',dx:2,dy:-2} },
      { x:1, y:2, op:{k:'x',a:'d1'} },
      { x:2, y:2, op:{k:'m',dx:2,dy:2} },
      { x:3, y:2, op:{k:'r',d:90} },
      { x:4, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:6, y:2, op:{k:'r',d:90} },
      { x:1, y:3, op:{k:'m',dx:-1,dy:-1} },
      { x:2, y:3, op:{k:'m',dx:1,dy:-1} },
      { x:4, y:3, op:{k:'r',d:90} },
      { x:5, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:6, y:3, op:{k:'r',d:-90} },
      { x:0, y:4, op:{k:'m',dx:1,dy:-1} },
      { x:1, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:2,dy:-2} },
      { x:4, y:4, op:{k:'x',a:'v'} },
      { x:5, y:4, op:{k:'x',a:'v'} },
      { x:3, y:5, op:{k:'m',dx:2,dy:0} },
      { x:5, y:5, op:{k:'r',d:-90} },
      { x:4, y:6, op:{k:'m',dx:1,dy:1} },
    ]
  },
  {
    id: 'q41', n: 41, act: 8, name: "La lunga", par: 12,
    hint: "",
    cols: 8, rows: 8,
    shape: [[3,4],[3,5],[3,6],[3,7],[4,7]],
    target: [[1,3],[1,4],[1,5],[0,6],[1,6]],
    walls: [[5,1],[2,3]],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:3} },
      { x:2, y:0, op:{k:'m',dx:-3,dy:0} },
      { x:3, y:0, op:{k:'m',dx:0,dy:-3} },
      { x:4, y:0, op:{k:'m',dx:0,dy:2} },
      { x:7, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:1, op:{k:'m',dx:0,dy:3} },
      { x:4, y:1, op:{k:'m',dx:3,dy:0} },
      { x:6, y:1, op:{k:'m',dx:2,dy:0} },
      { x:7, y:1, op:{k:'m',dx:1,dy:0} },
      { x:0, y:2, op:{k:'x',a:'v'} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-3} },
      { x:7, y:2, op:{k:'x',a:'v'} },
      { x:0, y:3, op:{k:'r',d:-90} },
      { x:1, y:3, op:{k:'m',dx:3,dy:0} },
      { x:3, y:3, op:{k:'m',dx:2,dy:0} },
      { x:4, y:3, op:{k:'x',a:'d1'} },
      { x:5, y:3, op:{k:'x',a:'d1'} },
      { x:6, y:3, op:{k:'m',dx:0,dy:2} },
      { x:7, y:3, op:{k:'m',dx:3,dy:0} },
      { x:0, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:4, op:{k:'x',a:'d2'} },
      { x:2, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:4, op:{k:'x',a:'v'} },
      { x:4, y:4, op:{k:'m',dx:-3,dy:0} },
      { x:6, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:7, y:4, op:{k:'m',dx:0,dy:3} },
      { x:3, y:5, op:{k:'x',a:'d1'} },
      { x:4, y:5, op:{k:'m',dx:0,dy:-3} },
      { x:5, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:5, op:{k:'x',a:'d1'} },
      { x:7, y:5, op:{k:'m',dx:0,dy:1} },
      { x:0, y:6, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:6, op:{k:'r',d:-90} },
      { x:2, y:6, op:{k:'m',dx:0,dy:2} },
      { x:3, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:6, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:6, op:{k:'m',dx:-3,dy:0} },
      { x:6, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:7, y:6, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:7, op:{k:'x',a:'d2'} },
      { x:1, y:7, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:7, op:{k:'m',dx:3,dy:0} },
      { x:5, y:7, op:{k:'x',a:'d2'} },
      { x:6, y:7, op:{k:'x',a:'d1'} },
      { x:7, y:7, op:{k:'m',dx:0,dy:-1} },
    ]
  },
  {
    id: 'q42', n: 42, act: 8, name: "Il labirinto", par: 13,
    hint: "",
    cols: 8, rows: 8,
    shape: [[6,1],[5,2],[6,2],[5,3],[5,4]],
    target: [[0,4],[1,4],[1,5],[2,5],[3,5]],
    walls: [[2,4],[6,6]],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:0, op:{k:'m',dx:-2,dy:-2} },
      { x:2, y:0, op:{k:'r',d:90} },
      { x:3, y:0, op:{k:'m',dx:0,dy:1} },
      { x:4, y:0, op:{k:'x',a:'v'} },
      { x:5, y:0, op:{k:'m',dx:1,dy:1} },
      { x:6, y:0, op:{k:'m',dx:-1,dy:-1} },
      { x:7, y:0, op:{k:'r',d:-90} },
      { x:0, y:1, op:{k:'m',dx:-1,dy:-1} },
      { x:1, y:1, op:{k:'m',dx:0,dy:2} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:1} },
      { x:3, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:1, op:{k:'x',a:'h'} },
      { x:5, y:1, op:{k:'m',dx:-2,dy:2} },
      { x:6, y:1, op:{k:'m',dx:-2,dy:2} },
      { x:7, y:1, op:{k:'m',dx:-2,dy:2} },
      { x:0, y:2, op:{k:'r',d:180} },
      { x:1, y:2, op:{k:'r',d:-90} },
      { x:3, y:2, op:{k:'m',dx:-2,dy:-2} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:1} },
      { x:6, y:2, op:{k:'m',dx:-1,dy:-1} },
      { x:7, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'m',dx:2,dy:-2} },
      { x:3, y:3, op:{k:'x',a:'h'} },
      { x:4, y:3, op:{k:'m',dx:1,dy:-1} },
      { x:5, y:3, op:{k:'r',d:180} },
      { x:7, y:3, op:{k:'x',a:'h'} },
      { x:0, y:4, op:{k:'x',a:'d1'} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:4, op:{k:'m',dx:-2,dy:-2} },
      { x:4, y:4, op:{k:'x',a:'h'} },
      { x:5, y:4, op:{k:'m',dx:-2,dy:-2} },
      { x:6, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:5, op:{k:'r',d:90} },
      { x:4, y:5, op:{k:'m',dx:-2,dy:2} },
      { x:5, y:5, op:{k:'r',d:180} },
      { x:7, y:5, op:{k:'x',a:'d2'} },
      { x:0, y:6, op:{k:'m',dx:1,dy:1} },
      { x:1, y:6, op:{k:'x',a:'d2'} },
      { x:2, y:6, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:6, op:{k:'x',a:'v'} },
      { x:4, y:6, op:{k:'m',dx:2,dy:2} },
      { x:5, y:6, op:{k:'x',a:'v'} },
      { x:0, y:7, op:{k:'x',a:'h'} },
      { x:1, y:7, op:{k:'x',a:'d1'} },
      { x:2, y:7, op:{k:'m',dx:-1,dy:1} },
      { x:3, y:7, op:{k:'m',dx:-1,dy:-1} },
      { x:4, y:7, op:{k:'m',dx:0,dy:1} },
      { x:6, y:7, op:{k:'r',d:180} },
    ]
  },
  {
    id: 'q43', n: 43, act: 8, name: "La spirale", par: 13,
    hint: "",
    cols: 8, rows: 8,
    shape: [[5,0],[5,1],[6,1],[6,2],[7,2]],
    target: [[4,2],[5,2],[5,3],[6,3],[6,4]],
    walls: [[1,1],[1,5],[6,5]],
    buttons: [
      { x:2, y:0, op:{k:'m',dx:-1,dy:-1} },
      { x:3, y:0, op:{k:'x',a:'v'} },
      { x:4, y:0, op:{k:'x',a:'v'} },
      { x:5, y:0, op:{k:'m',dx:-1,dy:-1} },
      { x:2, y:1, op:{k:'m',dx:0,dy:2} },
      { x:3, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:1, op:{k:'x',a:'d2'} },
      { x:6, y:1, op:{k:'x',a:'d2'} },
      { x:7, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:2, op:{k:'m',dx:-1,dy:-1} },
      { x:1, y:2, op:{k:'m',dx:2,dy:2} },
      { x:2, y:2, op:{k:'r',d:-90} },
      { x:3, y:2, op:{k:'m',dx:2,dy:2} },
      { x:5, y:2, op:{k:'m',dx:2,dy:-2} },
      { x:6, y:2, op:{k:'m',dx:-2,dy:2} },
      { x:7, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'r',d:-90} },
      { x:2, y:3, op:{k:'r',d:180} },
      { x:4, y:3, op:{k:'m',dx:1,dy:-1} },
      { x:5, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:3, op:{k:'m',dx:-2,dy:2} },
      { x:7, y:3, op:{k:'m',dx:2,dy:-2} },
      { x:2, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:4, op:{k:'r',d:-90} },
      { x:4, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:4, op:{k:'m',dx:1,dy:0} },
      { x:6, y:4, op:{k:'x',a:'h'} },
      { x:7, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:5, op:{k:'m',dx:-1,dy:-1} },
      { x:3, y:5, op:{k:'r',d:-90} },
      { x:4, y:5, op:{k:'x',a:'h'} },
      { x:2, y:6, op:{k:'x',a:'h'} },
      { x:4, y:6, op:{k:'m',dx:-2,dy:2} },
      { x:5, y:6, op:{k:'m',dx:-1,dy:1} },
      { x:6, y:6, op:{k:'x',a:'h'} },
      { x:2, y:7, op:{k:'m',dx:-1,dy:-1} },
      { x:3, y:7, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:7, op:{k:'m',dx:-2,dy:2} },
      { x:5, y:7, op:{k:'m',dx:-1,dy:-1} },
      { x:6, y:7, op:{k:'m',dx:2,dy:2} },
    ]
  },
  {
    id: 'q44', n: 44, act: 8, name: "Opera", par: 13,
    hint: "",
    cols: 8, rows: 8,
    shape: [[5,0],[6,0],[4,1],[5,1],[5,2]],
    target: [[1,2],[2,2],[2,3],[3,3],[2,4]],
    walls: [[5,3],[1,6],[2,6]],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:2, y:0, op:{k:'m',dx:1,dy:1} },
      { x:3, y:0, op:{k:'m',dx:2,dy:0} },
      { x:4, y:0, op:{k:'r',d:180} },
      { x:5, y:0, op:{k:'m',dx:0,dy:1} },
      { x:6, y:0, op:{k:'x',a:'v'} },
      { x:7, y:0, op:{k:'m',dx:0,dy:1} },
      { x:0, y:1, op:{k:'x',a:'h'} },
      { x:1, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:1, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:1, op:{k:'x',a:'v'} },
      { x:4, y:1, op:{k:'r',d:180} },
      { x:5, y:1, op:{k:'r',d:-90} },
      { x:6, y:1, op:{k:'x',a:'d2'} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:3, y:2, op:{k:'r',d:90} },
      { x:4, y:2, op:{k:'m',dx:2,dy:0} },
      { x:5, y:2, op:{k:'x',a:'v'} },
      { x:6, y:2, op:{k:'r',d:90} },
      { x:7, y:2, op:{k:'r',d:180} },
      { x:3, y:3, op:{k:'m',dx:2,dy:-2} },
      { x:4, y:3, op:{k:'m',dx:1,dy:0} },
      { x:6, y:3, op:{k:'x',a:'h'} },
      { x:7, y:3, op:{k:'m',dx:-1,dy:-1} },
      { x:0, y:4, op:{k:'r',d:-90} },
      { x:3, y:4, op:{k:'m',dx:2,dy:-2} },
      { x:4, y:4, op:{k:'r',d:90} },
      { x:2, y:5, op:{k:'x',a:'h'} },
      { x:4, y:5, op:{k:'m',dx:2,dy:0} },
      { x:6, y:5, op:{k:'m',dx:2,dy:2} },
      { x:7, y:5, op:{k:'r',d:-90} },
      { x:4, y:6, op:{k:'m',dx:0,dy:2} },
      { x:5, y:6, op:{k:'x',a:'h'} },
      { x:6, y:6, op:{k:'x',a:'d1'} },
      { x:7, y:6, op:{k:'m',dx:-2,dy:-2} },
      { x:5, y:7, op:{k:'m',dx:-2,dy:2} },
      { x:6, y:7, op:{k:'m',dx:2,dy:-2} },
    ]
  }
];

if (typeof module !== 'undefined' && module.exports)
  module.exports = { levels: OPERA_LEVELS, acts: OPERA_ACTS };
