/* Opera — i venti quadri. Ogni livello e' verificato con una ricerca esaustiva
   in ampiezza: 'par' e' il numero minimo di mosse per risolverlo. */
var OPERA_LEVELS = [
  {
    id: 'p1', n: 1, name: "Primo passo", par: 4,
    hint: "Le punte spostano la figura. Un quadretto si può premere solo se la figura ci sta sopra.",
    cols: 5, rows: 5,
    shape: [[2,4],[3,4]],
    target: [[3,1],[4,1]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:1,dy:0} },
      { x:1, y:0, op:{k:'m',dx:0,dy:1} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:1, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:2,dy:0} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:2, op:{k:'m',dx:0,dy:1} },
      { x:2, y:2, op:{k:'m',dx:1,dy:0} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:2, op:{k:'m',dx:0,dy:2} },
      { x:1, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:4, op:{k:'m',dx:0,dy:1} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:4, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'p2', n: 2, name: "La rincorsa", par: 5,
    hint: "Il numero di punte dice di quante caselle ci si sposta.",
    cols: 5, rows: 5,
    shape: [[3,1],[4,1]],
    target: [[1,2],[2,2]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:0, op:{k:'m',dx:0,dy:3} },
      { x:3, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:1, op:{k:'m',dx:0,dy:1} },
      { x:2, y:1, op:{k:'m',dx:-3,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:4, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:2, op:{k:'m',dx:0,dy:1} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-3} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:0} },
    ]
  },
  {
    id: 'p3', n: 3, name: "Un quarto di giro", par: 6,
    hint: "La freccia curva gira la figura di 90 gradi attorno al quadretto premuto.",
    cols: 5, rows: 5,
    shape: [[0,1],[1,1]],
    target: [[3,0],[3,1]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:0,dy:2} },
      { x:0, y:1, op:{k:'m',dx:0,dy:2} },
      { x:1, y:1, op:{k:'r',d:90} },
      { x:3, y:1, op:{k:'r',d:90} },
      { x:4, y:1, op:{k:'m',dx:0,dy:1} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:2, op:{k:'r',d:90} },
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:3, op:{k:'m',dx:0,dy:1} },
      { x:2, y:3, op:{k:'r',d:90} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:1, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-2} },
    ]
  },
  {
    id: 'p4', n: 4, name: "Il gomito", par: 7,
    hint: "Il perno della rotazione è il quadretto premuto: sceglierlo bene cambia tutto.",
    cols: 5, rows: 5,
    shape: [[1,3],[2,3],[2,4]],
    target: [[3,2],[2,3],[3,3]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:0, op:{k:'m',dx:0,dy:2} },
      { x:0, y:1, op:{k:'m',dx:2,dy:0} },
      { x:1, y:1, op:{k:'m',dx:0,dy:2} },
      { x:2, y:1, op:{k:'r',d:180} },
      { x:3, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:2, op:{k:'m',dx:0,dy:2} },
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'r',d:90} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:4, op:{k:'r',d:180} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:4, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'p5', n: 5, name: "Lo specchio", par: 7,
    hint: "L'asse tratteggiato ribalta la figura, e passa per il quadretto premuto.",
    cols: 6, rows: 6,
    shape: [[2,1],[3,1],[3,2]],
    target: [[4,2],[4,3],[5,3]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:0, op:{k:'m',dx:0,dy:1} },
      { x:2, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:2, op:{k:'x',a:'h'} },
      { x:1, y:2, op:{k:'x',a:'h'} },
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:2, op:{k:'m',dx:0,dy:2} },
      { x:4, y:2, op:{k:'m',dx:0,dy:2} },
      { x:5, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:3, op:{k:'m',dx:1,dy:0} },
      { x:3, y:3, op:{k:'m',dx:1,dy:0} },
      { x:4, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:4, op:{k:'m',dx:1,dy:0} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'x',a:'h'} },
      { x:4, y:4, op:{k:'x',a:'v'} },
      { x:1, y:5, op:{k:'x',a:'h'} },
      { x:2, y:5, op:{k:'x',a:'v'} },
      { x:3, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:5, op:{k:'x',a:'v'} },
    ]
  },
  {
    id: 'p6', n: 6, name: "Di sbieco", par: 7,
    hint: "Ci sono anche assi obliqui, a 45 gradi.",
    cols: 6, rows: 6,
    shape: [[1,3],[2,3],[2,4]],
    target: [[2,1],[2,2],[3,2]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'x',a:'d1'} },
      { x:1, y:0, op:{k:'m',dx:0,dy:2} },
      { x:2, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:0, op:{k:'m',dx:2,dy:0} },
      { x:0, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:1, op:{k:'m',dx:0,dy:1} },
      { x:3, y:1, op:{k:'x',a:'d2'} },
      { x:4, y:1, op:{k:'m',dx:0,dy:2} },
      { x:5, y:1, op:{k:'m',dx:0,dy:2} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:2, op:{k:'x',a:'d1'} },
      { x:5, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:3, op:{k:'x',a:'d1'} },
      { x:1, y:3, op:{k:'x',a:'d1'} },
      { x:2, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:3, op:{k:'m',dx:1,dy:0} },
      { x:4, y:3, op:{k:'x',a:'d2'} },
      { x:5, y:3, op:{k:'x',a:'d2'} },
      { x:0, y:4, op:{k:'x',a:'d1'} },
      { x:1, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:2,dy:0} },
      { x:3, y:4, op:{k:'x',a:'d1'} },
      { x:4, y:4, op:{k:'x',a:'d1'} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:5, op:{k:'m',dx:1,dy:0} },
      { x:3, y:5, op:{k:'x',a:'d1'} },
      { x:4, y:5, op:{k:'m',dx:2,dy:0} },
      { x:5, y:5, op:{k:'m',dx:-2,dy:0} },
    ]
  },
  {
    id: 'p7', n: 7, name: "Concerto", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[2,1],[2,2],[2,3],[3,3]],
    target: [[2,2],[3,2],[4,2],[4,3]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:0, op:{k:'x',a:'v'} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:0, op:{k:'r',d:90} },
      { x:0, y:1, op:{k:'m',dx:0,dy:-1} },
      { x:1, y:1, op:{k:'r',d:-90} },
      { x:2, y:1, op:{k:'m',dx:0,dy:2} },
      { x:3, y:1, op:{k:'x',a:'h'} },
      { x:4, y:1, op:{k:'x',a:'v'} },
      { x:0, y:2, op:{k:'r',d:90} },
      { x:1, y:2, op:{k:'x',a:'h'} },
      { x:2, y:2, op:{k:'x',a:'v'} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:3, op:{k:'m',dx:0,dy:2} },
      { x:1, y:3, op:{k:'r',d:90} },
      { x:2, y:3, op:{k:'x',a:'v'} },
      { x:3, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:4, op:{k:'x',a:'h'} },
      { x:1, y:4, op:{k:'r',d:-90} },
      { x:2, y:4, op:{k:'x',a:'v'} },
      { x:3, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:5, op:{k:'m',dx:0,dy:1} },
      { x:1, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:5, op:{k:'r',d:-90} },
    ]
  },
  {
    id: 'p8', n: 8, name: "La zeta", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[3,4],[4,4],[2,5],[3,5]],
    target: [[1,3],[1,4],[2,4],[2,5]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'x',a:'h'} },
      { x:1, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:0, y:1, op:{k:'m',dx:2,dy:0} },
      { x:1, y:1, op:{k:'m',dx:1,dy:0} },
      { x:3, y:1, op:{k:'r',d:-90} },
      { x:5, y:1, op:{k:'r',d:90} },
      { x:0, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:2, op:{k:'r',d:-90} },
      { x:4, y:2, op:{k:'x',a:'v'} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:2,dy:0} },
      { x:2, y:3, op:{k:'x',a:'h'} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:3, op:{k:'r',d:90} },
      { x:0, y:4, op:{k:'x',a:'v'} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:4, op:{k:'x',a:'h'} },
      { x:3, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:4, op:{k:'r',d:-90} },
      { x:5, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:5, op:{k:'r',d:90} },
      { x:2, y:5, op:{k:'x',a:'v'} },
      { x:3, y:5, op:{k:'x',a:'v'} },
      { x:4, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:5, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'p9', n: 9, name: "Il tridente", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[3,0],[4,0],[5,0],[4,1]],
    target: [[4,0],[4,1],[5,1],[4,2]],
    walls: [],
    buttons: [
      { x:1, y:0, op:{k:'r',d:180} },
      { x:2, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:3, y:0, op:{k:'m',dx:0,dy:2} },
      { x:4, y:0, op:{k:'m',dx:0,dy:2} },
      { x:0, y:1, op:{k:'m',dx:0,dy:3} },
      { x:1, y:1, op:{k:'x',a:'d1'} },
      { x:2, y:1, op:{k:'x',a:'d2'} },
      { x:3, y:1, op:{k:'r',d:90} },
      { x:4, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:1, op:{k:'x',a:'d2'} },
      { x:1, y:2, op:{k:'m',dx:0,dy:-3} },
      { x:2, y:2, op:{k:'x',a:'d2'} },
      { x:3, y:2, op:{k:'r',d:180} },
      { x:4, y:2, op:{k:'x',a:'d1'} },
      { x:0, y:3, op:{k:'m',dx:2,dy:0} },
      { x:1, y:3, op:{k:'m',dx:3,dy:0} },
      { x:3, y:3, op:{k:'r',d:180} },
      { x:4, y:3, op:{k:'r',d:90} },
      { x:5, y:3, op:{k:'m',dx:3,dy:0} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:1, y:4, op:{k:'m',dx:0,dy:2} },
      { x:3, y:4, op:{k:'m',dx:0,dy:2} },
      { x:4, y:4, op:{k:'x',a:'d1'} },
      { x:5, y:4, op:{k:'r',d:-90} },
      { x:1, y:5, op:{k:'r',d:90} },
      { x:3, y:5, op:{k:'m',dx:0,dy:-3} },
    ]
  },
  {
    id: 'p10', n: 10, name: "Doppio taglio", par: 9,
    hint: "",
    cols: 7, rows: 7,
    shape: [[4,3],[4,4],[3,5],[4,5]],
    target: [[1,3],[2,3],[2,4],[2,5]],
    walls: [],
    buttons: [
      { x:0, y:1, op:{k:'m',dx:3,dy:0} },
      { x:2, y:1, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:1, op:{k:'m',dx:-3,dy:0} },
      { x:4, y:1, op:{k:'x',a:'d2'} },
      { x:1, y:2, op:{k:'m',dx:2,dy:0} },
      { x:2, y:2, op:{k:'m',dx:0,dy:1} },
      { x:3, y:3, op:{k:'x',a:'d2'} },
      { x:4, y:3, op:{k:'x',a:'h'} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:4, op:{k:'m',dx:-3,dy:0} },
      { x:2, y:4, op:{k:'x',a:'h'} },
      { x:3, y:4, op:{k:'x',a:'d1'} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:5, op:{k:'m',dx:0,dy:2} },
      { x:1, y:5, op:{k:'x',a:'v'} },
      { x:2, y:5, op:{k:'x',a:'v'} },
      { x:3, y:5, op:{k:'x',a:'d1'} },
      { x:0, y:6, op:{k:'m',dx:0,dy:2} },
      { x:2, y:6, op:{k:'x',a:'d1'} },
      { x:3, y:6, op:{k:'m',dx:-3,dy:0} },
    ]
  },
  {
    id: 'p11', n: 11, name: "Il quadrato falso", par: 8,
    hint: "",
    cols: 6, rows: 6,
    shape: [[4,3],[5,3],[4,4],[5,4]],
    target: [[1,2],[2,2],[1,3],[2,3]],
    walls: [],
    buttons: [
      { x:0, y:1, op:{k:'m',dx:1,dy:1} },
      { x:1, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:1, op:{k:'m',dx:0,dy:2} },
      { x:3, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:1, op:{k:'m',dx:0,dy:1} },
      { x:0, y:2, op:{k:'m',dx:-1,dy:1} },
      { x:1, y:2, op:{k:'r',d:90} },
      { x:3, y:2, op:{k:'x',a:'d1'} },
      { x:5, y:2, op:{k:'m',dx:2,dy:-2} },
      { x:0, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:2} },
      { x:2, y:3, op:{k:'m',dx:2,dy:0} },
      { x:3, y:3, op:{k:'m',dx:0,dy:1} },
      { x:4, y:3, op:{k:'m',dx:2,dy:-2} },
      { x:5, y:3, op:{k:'m',dx:0,dy:1} },
      { x:0, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:4, op:{k:'x',a:'d1'} },
      { x:2, y:4, op:{k:'m',dx:1,dy:-1} },
      { x:3, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:4, op:{k:'x',a:'d2'} },
      { x:5, y:4, op:{k:'m',dx:-1,dy:-1} },
      { x:1, y:5, op:{k:'m',dx:-2,dy:2} },
      { x:4, y:5, op:{k:'x',a:'d1'} },
    ]
  },
  {
    id: 'p12', n: 12, name: "Effe", par: 10,
    hint: "",
    cols: 7, rows: 7,
    shape: [[2,2],[3,2],[1,3],[2,3],[2,4]],
    target: [[3,4],[3,5],[4,5],[2,6],[3,6]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:0, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:1, op:{k:'x',a:'v'} },
      { x:1, y:1, op:{k:'r',d:-90} },
      { x:2, y:1, op:{k:'x',a:'h'} },
      { x:3, y:1, op:{k:'r',d:90} },
      { x:4, y:1, op:{k:'x',a:'h'} },
      { x:0, y:2, op:{k:'m',dx:0,dy:2} },
      { x:1, y:2, op:{k:'m',dx:0,dy:1} },
      { x:2, y:2, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:2, op:{k:'m',dx:0,dy:2} },
      { x:5, y:2, op:{k:'m',dx:2,dy:0} },
      { x:0, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:3, op:{k:'x',a:'v'} },
      { x:2, y:3, op:{k:'x',a:'v'} },
      { x:3, y:3, op:{k:'x',a:'v'} },
      { x:4, y:3, op:{k:'m',dx:0,dy:1} },
      { x:0, y:4, op:{k:'m',dx:0,dy:1} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:4, op:{k:'x',a:'h'} },
      { x:0, y:5, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:5, op:{k:'x',a:'h'} },
      { x:3, y:5, op:{k:'r',d:-90} },
      { x:4, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:0, y:6, op:{k:'m',dx:0,dy:1} },
      { x:1, y:6, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:6, op:{k:'x',a:'h'} },
      { x:5, y:6, op:{k:'r',d:90} },
    ]
  },
  {
    id: 'p13', n: 13, name: "La enne", par: 9,
    hint: "",
    cols: 7, rows: 7,
    shape: [[5,2],[4,3],[5,3],[4,4],[4,5]],
    target: [[1,3],[1,4],[1,5],[2,5],[2,6]],
    walls: [],
    buttons: [
      { x:0, y:0, op:{k:'r',d:180} },
      { x:1, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:0, op:{k:'m',dx:1,dy:0} },
      { x:4, y:0, op:{k:'m',dx:0,dy:2} },
      { x:5, y:0, op:{k:'x',a:'d1'} },
      { x:3, y:1, op:{k:'x',a:'d2'} },
      { x:4, y:1, op:{k:'m',dx:0,dy:3} },
      { x:5, y:1, op:{k:'m',dx:1,dy:0} },
      { x:6, y:1, op:{k:'r',d:180} },
      { x:0, y:2, op:{k:'m',dx:0,dy:3} },
      { x:1, y:2, op:{k:'m',dx:3,dy:0} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:3, y:2, op:{k:'m',dx:1,dy:0} },
      { x:4, y:2, op:{k:'x',a:'d1'} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:3, op:{k:'m',dx:0,dy:1} },
      { x:3, y:3, op:{k:'r',d:180} },
      { x:4, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:3, op:{k:'r',d:-90} },
      { x:6, y:3, op:{k:'m',dx:3,dy:0} },
      { x:0, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:4, op:{k:'x',a:'d2'} },
      { x:3, y:4, op:{k:'x',a:'d2'} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:4, op:{k:'m',dx:2,dy:0} },
      { x:0, y:5, op:{k:'r',d:90} },
      { x:2, y:5, op:{k:'x',a:'d2'} },
      { x:3, y:5, op:{k:'x',a:'d1'} },
      { x:4, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:5, op:{k:'m',dx:-3,dy:0} },
      { x:0, y:6, op:{k:'r',d:90} },
      { x:1, y:6, op:{k:'x',a:'d2'} },
      { x:4, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:6, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:6, op:{k:'m',dx:-1,dy:0} },
    ]
  },
  {
    id: 'p14', n: 14, name: "La ipsilon", par: 11,
    hint: "",
    cols: 7, rows: 7,
    shape: [[3,2],[2,3],[3,3],[3,4],[3,5]],
    target: [[1,3],[1,4],[2,4],[1,5],[1,6]],
    walls: [],
    buttons: [
      { x:2, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:0, op:{k:'m',dx:1,dy:0} },
      { x:5, y:0, op:{k:'x',a:'d1'} },
      { x:1, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:2, y:1, op:{k:'m',dx:1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:6, y:1, op:{k:'r',d:-90} },
      { x:0, y:2, op:{k:'x',a:'d1'} },
      { x:1, y:2, op:{k:'x',a:'v'} },
      { x:2, y:2, op:{k:'x',a:'v'} },
      { x:3, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:2, op:{k:'x',a:'d2'} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:3, op:{k:'x',a:'v'} },
      { x:3, y:3, op:{k:'x',a:'h'} },
      { x:6, y:3, op:{k:'x',a:'h'} },
      { x:0, y:4, op:{k:'m',dx:0,dy:1} },
      { x:1, y:4, op:{k:'r',d:-90} },
      { x:2, y:4, op:{k:'m',dx:1,dy:0} },
      { x:4, y:4, op:{k:'x',a:'h'} },
      { x:0, y:5, op:{k:'x',a:'d1'} },
      { x:1, y:5, op:{k:'r',d:-90} },
      { x:2, y:5, op:{k:'r',d:90} },
      { x:3, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:5, op:{k:'x',a:'h'} },
      { x:0, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:6, op:{k:'m',dx:1,dy:0} },
      { x:3, y:6, op:{k:'m',dx:0,dy:1} },
      { x:4, y:6, op:{k:'r',d:90} },
      { x:6, y:6, op:{k:'m',dx:2,dy:0} },
    ]
  },
  {
    id: 'p15', n: 15, name: "La doppia vu", par: 8,
    hint: "Le caselle scure sono muri: la figura non ci può passare sopra.",
    cols: 7, rows: 7,
    shape: [[1,2],[1,3],[2,3],[2,4],[3,4]],
    target: [[3,0],[2,1],[3,1],[1,2],[2,2]],
    walls: [[3,3]],
    buttons: [
      { x:0, y:0, op:{k:'x',a:'h'} },
      { x:2, y:0, op:{k:'m',dx:0,dy:2} },
      { x:3, y:0, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:0, op:{k:'r',d:90} },
      { x:0, y:1, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:1, op:{k:'r',d:90} },
      { x:2, y:1, op:{k:'m',dx:0,dy:1} },
      { x:3, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:1, op:{k:'m',dx:1,dy:0} },
      { x:0, y:2, op:{k:'m',dx:0,dy:1} },
      { x:1, y:2, op:{k:'x',a:'h'} },
      { x:2, y:2, op:{k:'x',a:'h'} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:2, op:{k:'m',dx:0,dy:2} },
      { x:0, y:3, op:{k:'r',d:-90} },
      { x:1, y:3, op:{k:'m',dx:0,dy:2} },
      { x:2, y:3, op:{k:'r',d:90} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:3, op:{k:'m',dx:2,dy:0} },
      { x:0, y:4, op:{k:'m',dx:0,dy:1} },
      { x:1, y:4, op:{k:'x',a:'h'} },
      { x:2, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:4, op:{k:'x',a:'h'} },
      { x:4, y:4, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:4, op:{k:'x',a:'v'} },
      { x:6, y:4, op:{k:'m',dx:0,dy:1} },
      { x:0, y:5, op:{k:'m',dx:0,dy:1} },
      { x:2, y:5, op:{k:'m',dx:2,dy:0} },
      { x:4, y:5, op:{k:'m',dx:0,dy:1} },
      { x:5, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:1, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:6, op:{k:'x',a:'v'} },
      { x:3, y:6, op:{k:'m',dx:2,dy:0} },
      { x:4, y:6, op:{k:'r',d:-90} },
      { x:6, y:6, op:{k:'m',dx:-2,dy:0} },
    ]
  },
  {
    id: 'p16', n: 16, name: "La zeta lunga", par: 11,
    hint: "",
    cols: 7, rows: 7,
    shape: [[2,1],[3,1],[3,2],[3,3],[4,3]],
    target: [[5,4],[6,4],[5,5],[4,6],[5,6]],
    walls: [[0,0],[6,6]],
    buttons: [
      { x:1, y:0, op:{k:'m',dx:3,dy:0} },
      { x:5, y:0, op:{k:'r',d:90} },
      { x:0, y:1, op:{k:'r',d:90} },
      { x:1, y:1, op:{k:'r',d:-90} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:2} },
      { x:4, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:1, op:{k:'r',d:90} },
      { x:6, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:0, y:2, op:{k:'x',a:'d2'} },
      { x:1, y:2, op:{k:'m',dx:3,dy:0} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:3, y:2, op:{k:'r',d:180} },
      { x:4, y:2, op:{k:'x',a:'d2'} },
      { x:6, y:2, op:{k:'m',dx:0,dy:3} },
      { x:1, y:3, op:{k:'m',dx:1,dy:0} },
      { x:2, y:3, op:{k:'x',a:'d1'} },
      { x:3, y:3, op:{k:'m',dx:0,dy:3} },
      { x:4, y:3, op:{k:'m',dx:-3,dy:0} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:6, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:4, op:{k:'x',a:'d1'} },
      { x:4, y:4, op:{k:'m',dx:1,dy:0} },
      { x:5, y:4, op:{k:'x',a:'d2'} },
      { x:6, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:5, op:{k:'m',dx:0,dy:1} },
      { x:5, y:5, op:{k:'m',dx:3,dy:0} },
      { x:6, y:5, op:{k:'m',dx:0,dy:3} },
      { x:3, y:6, op:{k:'r',d:-90} },
      { x:4, y:6, op:{k:'m',dx:0,dy:-3} },
    ]
  },
  {
    id: 'p17', n: 17, name: "Ferro di cavallo", par: 9,
    hint: "",
    cols: 7, rows: 7,
    shape: [[4,3],[6,3],[4,4],[5,4],[6,4]],
    target: [[0,5],[1,5],[2,5],[0,6],[2,6]],
    walls: [[3,0],[3,6]],
    buttons: [
      { x:2, y:0, op:{k:'m',dx:-2,dy:2} },
      { x:2, y:1, op:{k:'m',dx:1,dy:1} },
      { x:3, y:1, op:{k:'m',dx:0,dy:1} },
      { x:4, y:1, op:{k:'m',dx:0,dy:2} },
      { x:0, y:2, op:{k:'m',dx:2,dy:0} },
      { x:1, y:2, op:{k:'m',dx:0,dy:2} },
      { x:3, y:2, op:{k:'m',dx:0,dy:-1} },
      { x:4, y:2, op:{k:'x',a:'h'} },
      { x:5, y:2, op:{k:'m',dx:-1,dy:1} },
      { x:0, y:3, op:{k:'m',dx:-2,dy:2} },
      { x:2, y:3, op:{k:'x',a:'h'} },
      { x:3, y:3, op:{k:'x',a:'v'} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:0} },
      { x:5, y:3, op:{k:'m',dx:2,dy:0} },
      { x:6, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:2, y:4, op:{k:'m',dx:-1,dy:-1} },
      { x:3, y:4, op:{k:'x',a:'h'} },
      { x:4, y:4, op:{k:'x',a:'d1'} },
      { x:6, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:0, y:5, op:{k:'r',d:90} },
      { x:1, y:5, op:{k:'m',dx:2,dy:-2} },
      { x:4, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:5, op:{k:'x',a:'d1'} },
      { x:0, y:6, op:{k:'x',a:'v'} },
    ]
  },
  {
    id: 'p18', n: 18, name: "La lunga", par: 12,
    hint: "",
    cols: 8, rows: 8,
    shape: [[5,0],[5,1],[5,2],[5,3],[6,3]],
    target: [[5,4],[5,5],[5,6],[4,7],[5,7]],
    walls: [[7,0],[0,7]],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:0, op:{k:'m',dx:3,dy:0} },
      { x:2, y:0, op:{k:'m',dx:-3,dy:0} },
      { x:3, y:0, op:{k:'m',dx:2,dy:0} },
      { x:4, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:0, op:{k:'m',dx:1,dy:0} },
      { x:0, y:1, op:{k:'m',dx:3,dy:0} },
      { x:1, y:1, op:{k:'m',dx:0,dy:3} },
      { x:2, y:1, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:1, op:{k:'m',dx:0,dy:3} },
      { x:4, y:1, op:{k:'m',dx:0,dy:1} },
      { x:5, y:1, op:{k:'m',dx:-3,dy:0} },
      { x:6, y:1, op:{k:'m',dx:2,dy:0} },
      { x:7, y:1, op:{k:'m',dx:1,dy:0} },
      { x:0, y:2, op:{k:'r',d:90} },
      { x:1, y:2, op:{k:'m',dx:-1,dy:0} },
      { x:2, y:2, op:{k:'m',dx:2,dy:0} },
      { x:4, y:2, op:{k:'m',dx:0,dy:2} },
      { x:5, y:2, op:{k:'m',dx:0,dy:1} },
      { x:6, y:2, op:{k:'m',dx:-2,dy:0} },
      { x:7, y:2, op:{k:'m',dx:0,dy:2} },
      { x:0, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:2, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:3, op:{k:'m',dx:0,dy:-3} },
      { x:5, y:3, op:{k:'x',a:'h'} },
      { x:6, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:7, y:3, op:{k:'m',dx:1,dy:0} },
      { x:0, y:4, op:{k:'m',dx:0,dy:3} },
      { x:1, y:4, op:{k:'x',a:'h'} },
      { x:3, y:4, op:{k:'m',dx:-2,dy:0} },
      { x:4, y:4, op:{k:'r',d:-90} },
      { x:6, y:4, op:{k:'m',dx:0,dy:3} },
      { x:0, y:5, op:{k:'x',a:'v'} },
      { x:1, y:5, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:5, op:{k:'m',dx:2,dy:0} },
      { x:4, y:5, op:{k:'r',d:90} },
      { x:5, y:5, op:{k:'m',dx:0,dy:-3} },
      { x:6, y:5, op:{k:'r',d:-90} },
      { x:7, y:5, op:{k:'m',dx:-3,dy:0} },
      { x:0, y:6, op:{k:'m',dx:-3,dy:0} },
      { x:1, y:6, op:{k:'x',a:'h'} },
      { x:2, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:6, op:{k:'m',dx:-3,dy:0} },
      { x:4, y:6, op:{k:'m',dx:0,dy:-3} },
      { x:5, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:7, y:6, op:{k:'x',a:'h'} },
      { x:1, y:7, op:{k:'m',dx:0,dy:3} },
      { x:4, y:7, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:7, op:{k:'r',d:90} },
      { x:7, y:7, op:{k:'m',dx:3,dy:0} },
    ]
  },
  {
    id: 'p19', n: 19, name: "La croce", par: 11,
    hint: "",
    cols: 8, rows: 8,
    shape: [[5,3],[6,3],[7,3],[6,4],[6,5]],
    target: [[5,5],[3,6],[4,6],[5,6],[5,7]],
    walls: [[3,3],[4,4]],
    buttons: [
      { x:0, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:3, y:0, op:{k:'m',dx:-1,dy:0} },
      { x:5, y:0, op:{k:'m',dx:1,dy:-1} },
      { x:6, y:0, op:{k:'m',dx:-2,dy:2} },
      { x:0, y:1, op:{k:'m',dx:-1,dy:1} },
      { x:2, y:1, op:{k:'r',d:180} },
      { x:3, y:1, op:{k:'m',dx:-1,dy:-1} },
      { x:4, y:1, op:{k:'r',d:-90} },
      { x:5, y:1, op:{k:'m',dx:-1,dy:-1} },
      { x:0, y:2, op:{k:'m',dx:2,dy:-2} },
      { x:2, y:2, op:{k:'x',a:'d1'} },
      { x:3, y:2, op:{k:'m',dx:1,dy:0} },
      { x:4, y:2, op:{k:'m',dx:2,dy:0} },
      { x:5, y:2, op:{k:'m',dx:-2,dy:-2} },
      { x:6, y:2, op:{k:'m',dx:-1,dy:1} },
      { x:0, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:1, y:3, op:{k:'m',dx:0,dy:-2} },
      { x:2, y:3, op:{k:'x',a:'d1'} },
      { x:4, y:3, op:{k:'m',dx:-2,dy:2} },
      { x:5, y:3, op:{k:'m',dx:-2,dy:2} },
      { x:6, y:3, op:{k:'m',dx:-1,dy:-1} },
      { x:7, y:3, op:{k:'m',dx:1,dy:-1} },
      { x:0, y:4, op:{k:'m',dx:1,dy:1} },
      { x:1, y:4, op:{k:'m',dx:1,dy:1} },
      { x:3, y:4, op:{k:'m',dx:-2,dy:-2} },
      { x:5, y:4, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:4, op:{k:'x',a:'v'} },
      { x:0, y:5, op:{k:'x',a:'h'} },
      { x:1, y:5, op:{k:'m',dx:-1,dy:-1} },
      { x:2, y:5, op:{k:'x',a:'h'} },
      { x:3, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:4, y:5, op:{k:'x',a:'h'} },
      { x:5, y:5, op:{k:'x',a:'h'} },
      { x:6, y:5, op:{k:'m',dx:2,dy:0} },
      { x:7, y:5, op:{k:'r',d:90} },
      { x:0, y:6, op:{k:'m',dx:2,dy:-2} },
      { x:2, y:6, op:{k:'x',a:'d1'} },
      { x:3, y:6, op:{k:'m',dx:1,dy:0} },
      { x:5, y:6, op:{k:'x',a:'v'} },
      { x:0, y:7, op:{k:'m',dx:-1,dy:1} },
      { x:2, y:7, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:7, op:{k:'m',dx:0,dy:-2} },
      { x:4, y:7, op:{k:'m',dx:1,dy:-1} },
      { x:5, y:7, op:{k:'m',dx:2,dy:-2} },
      { x:6, y:7, op:{k:'m',dx:1,dy:0} },
      { x:7, y:7, op:{k:'x',a:'d2'} },
    ]
  },
  {
    id: 'p20', n: 20, name: "Opera", par: 14,
    hint: "",
    cols: 8, rows: 8,
    shape: [[5,0],[6,0],[4,1],[5,1],[5,2]],
    target: [[1,0],[0,1],[1,1],[2,1],[0,2]],
    walls: [[0,0],[7,0],[0,7],[7,7]],
    buttons: [
      { x:2, y:0, op:{k:'x',a:'d2'} },
      { x:3, y:0, op:{k:'r',d:180} },
      { x:4, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:6, y:0, op:{k:'m',dx:0,dy:-2} },
      { x:0, y:1, op:{k:'m',dx:-2,dy:0} },
      { x:1, y:1, op:{k:'m',dx:1,dy:-1} },
      { x:2, y:1, op:{k:'r',d:180} },
      { x:3, y:1, op:{k:'m',dx:2,dy:0} },
      { x:4, y:1, op:{k:'x',a:'v'} },
      { x:5, y:1, op:{k:'x',a:'h'} },
      { x:6, y:1, op:{k:'m',dx:-2,dy:-2} },
      { x:0, y:2, op:{k:'r',d:90} },
      { x:2, y:2, op:{k:'m',dx:2,dy:2} },
      { x:3, y:2, op:{k:'m',dx:2,dy:2} },
      { x:4, y:2, op:{k:'m',dx:2,dy:0} },
      { x:5, y:2, op:{k:'x',a:'v'} },
      { x:6, y:2, op:{k:'m',dx:-1,dy:-1} },
      { x:7, y:2, op:{k:'x',a:'d1'} },
      { x:0, y:3, op:{k:'m',dx:-2,dy:2} },
      { x:1, y:3, op:{k:'m',dx:0,dy:2} },
      { x:4, y:3, op:{k:'m',dx:0,dy:-1} },
      { x:5, y:3, op:{k:'m',dx:-1,dy:0} },
      { x:6, y:3, op:{k:'m',dx:0,dy:1} },
      { x:7, y:3, op:{k:'m',dx:-2,dy:-2} },
      { x:0, y:4, op:{k:'m',dx:2,dy:0} },
      { x:1, y:4, op:{k:'x',a:'h'} },
      { x:2, y:4, op:{k:'m',dx:0,dy:1} },
      { x:3, y:4, op:{k:'m',dx:2,dy:-2} },
      { x:4, y:4, op:{k:'m',dx:0,dy:-2} },
      { x:5, y:4, op:{k:'m',dx:2,dy:2} },
      { x:0, y:5, op:{k:'m',dx:2,dy:0} },
      { x:1, y:5, op:{k:'m',dx:-1,dy:-1} },
      { x:2, y:5, op:{k:'m',dx:0,dy:-1} },
      { x:3, y:5, op:{k:'x',a:'h'} },
      { x:4, y:5, op:{k:'m',dx:-2,dy:-2} },
      { x:7, y:5, op:{k:'m',dx:-1,dy:0} },
      { x:0, y:6, op:{k:'m',dx:-1,dy:1} },
      { x:1, y:6, op:{k:'m',dx:-2,dy:2} },
      { x:2, y:6, op:{k:'m',dx:1,dy:0} },
      { x:3, y:6, op:{k:'m',dx:2,dy:0} },
      { x:4, y:6, op:{k:'x',a:'d2'} },
      { x:5, y:6, op:{k:'m',dx:0,dy:-1} },
      { x:6, y:6, op:{k:'m',dx:-2,dy:2} },
      { x:7, y:6, op:{k:'m',dx:0,dy:-2} },
      { x:3, y:7, op:{k:'m',dx:1,dy:-1} },
      { x:4, y:7, op:{k:'m',dx:2,dy:2} },
      { x:5, y:7, op:{k:'m',dx:0,dy:1} },
    ]
  }
];

if (typeof module !== 'undefined' && module.exports) module.exports = OPERA_LEVELS;
